### PR TITLE
fix: ScrollX when there's only one picture

### PR DESCRIPTION
**Pull request by MonsterAnan**
fix: When I only have one picture , scroll horizontal picture is hidden.
I fix it. 
[Watch the Bug Demo](https://upload.42how.com/article/202108051523-bug.mp4)

### CODE REVIEW

**Comment by pavelbabenko** [comment]
Hi @MonsterAnan 
Thank you for the pull request
Could you write which props are you using and what is the `data.length` so I can reproduce the bug?

**Comment by MonsterAnan** [comment]
thank you reply.
Is this,I copy you project demo.
this is Photos Screen params:
```
...
 const { params } = useRoute<RouteProp<RootParamList, "photos">>() 
 // params = {"images": ["https://upload.42how.com/article/weibo_1627448462288.jpg"], "index": 0}
...
  return (
    <View style={styles.container}>
      <AwesomeGallery
        data={params?.images.map((uri) => ({ uri }))}
        keyExtractor={(item) => item.uri}
        renderItem={renderItem}
        initialIndex={params.index}
        onIndexChange={onIndexChange}
        onSwipeToClose={goBack}
      />
    </View>
  )


```
After that, it'll be just like yours code.

**Comment by pavelbabenko** [comment]
Fixed in [v0.2.1](https://github.com/Flair-Dev/react-native-awesome-gallery/releases/tag/v0.2.1)

**Comment by MonsterAnan** [comment]
ok, thank you

**Pull request closed without merging**
