### PR TITLE
feat: set index with animation, update reanimated to v3.2.0

### PR DESCRIPTION
**Pull request by lpatrun**
Hello,

loving this project because the solution is so complete.

I did notice the setIndex is not animated and also decided to bump reanimated version so it is up to date.

### CODE REVIEW

**Comment by Steve0929** [comment]
Bumping this as the newest expo SDK 49 is using reanimated v3

**Comment by KorayGocmen** [comment]
Bumping

**Comment by KorayGocmen** [comment]
Thanks @pavelbabenko! We'll update our packages with the new release 🙌

**Comment by pavelbabenko** [comment]
Released in [v0.3.6](https://github.com/pavelbabenko/react-native-awesome-gallery/releases/tag/v0.3.6)

**Comment by pavelbabenko** [comment]
Thanks everyone for this PR
It pushed me to continue working on the lib

**Pull request merged**
