### PR TITLE
feat: added RTL support

### PR DESCRIPTION
**Pull request by aleppos**

### CODE REVIEW

**Comment by aleppos** [comment]
@pavelbabenko can you take a look.

**Comment by pavelbabenko** [comment]
Hi @aleppos 
I would leave the choice of enabling rtl for developer
Could you make isRTL as prop of Gallery?
And please, test with other props, e.g loop

**Comment by FadiAboMsalam** [comment]
@pavelbabenko I don't think that making a prop of isRTL is necessary since the code only affects when I18nManager.isRTL is true so this won't affect the LTR devices and would help any RTL ones like my case 
BTW I tested the PR and it works great @aleppos  thank you

**Comment by pavelbabenko** [comment]
Implemented in [v0.3.3](https://github.com/Flair-Dev/react-native-awesome-gallery/releases/tag/v0.3.3)

**Pull request closed without merging**
